<?php 
      $tpls="includer/tpls";
      include("$tpls/header.php");
	  include("$tpls/menu.php");
	  include("$tpls/slider.php");
	  include("$tpls/about.php");
	  include("$tpls/footer_1.php");
	  include("$tpls/fixe_category.php");
	  include("$tpls/footer.php");
?>